services:
  - type: web
    name: n8n-cloud
    env: docker
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
    dockerCommand: "n8n start"
    buildCommand: ""
    rootDir: ""
